### ISSUE TITLE
Lunar crash

### ISSUE THREAD

**Issue by TristamaX** [Project-Lunar/Project-Lunar-Issue-Tracker#1]
I added a rom onto my Genesis mini, and it resulted in an error, rebooting my system. I decided to go into the Lunar settings and overclock it, which causes it to crash the second it enters the boot menu when i turn the console on.

**Comment by TristamaX** [comment]
its also not uninstalling Lunar either, so im worried this bricked my console.

**Comment by BigL1877** [comment]
im having the same issue. mine had the reboot isue and i also over clocked and now when i select lunar it goes black and freezes the system. i really hope my system is not bricked.

**Comment by BigL1877** [comment]
i belive it has to do with the amount of games. i erased a bunch so it has 5Omb of free space and its working. not sure how long but i will keep you posted.

**Comment by BigL1877** [comment]
so far its still working. i suggest that people always leave at least 5OMB extra space.

**Comment by BananaRama203** [comment]
@TristamaX This is likely due to a bad sync. Bricking is not possible. You are also likely trying to uninstall via FEL instead of normally. 

You will likely need to go and: restore local data from backup and resync and try again. If you still have issues just check into sega support channel for more help.
